// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using medicalassitent.web.Data;

namespace medicalassitent.web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190505060355_AddAnalitics")]
    partial class AddAnalitics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("medicalassitent.web.Data.Entities.Analytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ASO_Cuant");

                    b.Property<string>("ASO_Latex");

                    b.Property<string>("Ac_Urico");

                    b.Property<string>("Acido_Folico");

                    b.Property<string>("Albumina");

                    b.Property<string>("Alfp");

                    b.Property<string>("Amilasa");

                    b.Property<string>("Ana");

                    b.Property<string>("Ant_Feb");

                    b.Property<string>("AntiHav_Lgg");

                    b.Property<string>("AntiHbc");

                    b.Property<string>("AntiHbe");

                    b.Property<string>("Anti_Dna");

                    b.Property<string>("Anti_Hav");

                    b.Property<string>("Antic_Antit");

                    b.Property<string>("Antidoping_CocMar");

                    b.Property<string>("Antidoping_Panel");

                    b.Property<string>("Antigeno_Ag");

                    b.Property<string>("Bacil_En");

                    b.Property<string>("Bacil_Ser");

                    b.Property<string>("Billirubina");

                    b.Property<string>("C3");

                    b.Property<string>("C4");

                    b.Property<string>("Calcio");

                    b.Property<string>("Cap_Hierro");

                    b.Property<string>("Cea");

                    b.Property<string>("Cea_125");

                    b.Property<string>("Cea_15");

                    b.Property<string>("Cea_19");

                    b.Property<string>("Celulas_Le");

                    b.Property<string>("Ck_MB");

                    b.Property<string>("Ck_Total");

                    b.Property<string>("Cloro");

                    b.Property<string>("Col_HDL");

                    b.Property<string>("Col_LDL");

                    b.Property<string>("Col_Total");

                    b.Property<string>("Col_VLDL");

                    b.Property<string>("Colera");

                    b.Property<string>("Cont_Nasal");

                    b.Property<string>("Cont_Retic");

                    b.Property<string>("Cont_Sangre");

                    b.Property<string>("Coprologico");

                    b.Property<string>("Coprologico_Conc");

                    b.Property<string>("Coprologico_X2");

                    b.Property<string>("Coprologico_X3");

                    b.Property<string>("Cort_Muest");

                    b.Property<string>("Cort_Pm");

                    b.Property<string>("Cortisol");

                    b.Property<string>("Creatinina");

                    b.Property<string>("Cultivo");

                    b.Property<string>("CurGluc_Hora");

                    b.Property<string>("Dengue_Lgg");

                    b.Property<string>("Dengue_Lgm");

                    b.Property<string>("Depur_Creat");

                    b.Property<string>("Dig_Heces");

                    b.Property<string>("Dx");

                    b.Property<string>("Elect_Hb");

                    b.Property<string>("Elect_MAcid");

                    b.Property<string>("Eritrosedimentacion");

                    b.Property<string>("Estrogenos_Totales");

                    b.Property<string>("Examen_Orina");

                    b.Property<string>("Fac_Cuant");

                    b.Property<string>("Fac_Latex");

                    b.Property<string>("Falcemia");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Ferritina");

                    b.Property<string>("Fos_Alcalina");

                    b.Property<string>("FosfAcNoProst");

                    b.Property<string>("FosfAcProst");

                    b.Property<string>("FosfAcTotal");

                    b.Property<string>("Fosfolipidos");

                    b.Property<string>("Fosforo");

                    b.Property<string>("Fsh");

                    b.Property<string>("GGTP");

                    b.Property<string>("Gluc_Ayunas");

                    b.Property<string>("Gluc_Capilar");

                    b.Property<string>("Gluc_Gluc");

                    b.Property<string>("Gluc_Prandial");

                    b.Property<string>("HIV");

                    b.Property<string>("HTLV");

                    b.Property<string>("H_Pilory");

                    b.Property<string>("Hbcg");

                    b.Property<string>("Hem_Gluc");

                    b.Property<string>("Hemograma");

                    b.Property<string>("Hemotozoarios");

                    b.Property<string>("HepatB_Ag");

                    b.Property<string>("Hepat_HVC");

                    b.Property<string>("Hi_Serico");

                    b.Property<string>("Hormona_Basal");

                    b.Property<string>("Hormona_Est");

                    b.Property<int>("Id_Medico");

                    b.Property<int>("Id_Paciente");

                    b.Property<string>("Inm_Lgc");

                    b.Property<string>("Inm_Lgm");

                    b.Property<string>("Inm_lgA");

                    b.Property<string>("Inmunoglobina");

                    b.Property<string>("Ldh");

                    b.Property<string>("Lep_Lgg");

                    b.Property<string>("Lep_Lgm");

                    b.Property<string>("Lh");

                    b.Property<string>("Lip_Tot");

                    b.Property<string>("Lipasa");

                    b.Property<string>("Magnesio");

                    b.Property<string>("Microal_Cuant");

                    b.Property<string>("Monotest");

                    b.Property<string>("No_Historia");

                    b.Property<string>("Otros");

                    b.Property<string>("Oxiuros_Cinta");

                    b.Property<string>("PCR_Ultra");

                    b.Property<string>("Pcr_Latex");

                    b.Property<string>("Pcr__Cuant");

                    b.Property<string>("Potasio_K");

                    b.Property<string>("Progesterona");

                    b.Property<string>("Prolactina");

                    b.Property<string>("Prot_Frac");

                    b.Property<string>("Prot_Total");

                    b.Property<string>("Proteina_BJ");

                    b.Property<string>("Proteina_Orina");

                    b.Property<string>("Prueb_Directa");

                    b.Property<string>("Prueb_Indirecta");

                    b.Property<string>("Prueba_Orina");

                    b.Property<string>("Prueba_Sangre");

                    b.Property<string>("Rotavirus");

                    b.Property<string>("SGCT");

                    b.Property<string>("SGTP");

                    b.Property<string>("Sangre_Oculta");

                    b.Property<string>("Sodio_Na");

                    b.Property<string>("Sust_Reduc");

                    b.Property<string>("T3");

                    b.Property<string>("T3_Libre");

                    b.Property<string>("T4");

                    b.Property<string>("T4_Libre");

                    b.Property<string>("Tb_Micodot");

                    b.Property<string>("Testoterona");

                    b.Property<string>("Tiemp_Coag");

                    b.Property<string>("Tiemp_Prot");

                    b.Property<string>("Tiemp_Sang");

                    b.Property<string>("Tiemp__Tromb");

                    b.Property<string>("TincGram_en");

                    b.Property<string>("Tip_Sang");

                    b.Property<string>("Tiroglobulina");

                    b.Property<string>("Toxo_Lgg");

                    b.Property<string>("Toxo_Lgm");

                    b.Property<string>("Trigliceridos");

                    b.Property<string>("TropT_Cualit");

                    b.Property<string>("TropT_Cuanti");

                    b.Property<string>("Tropl_Cualit");

                    b.Property<string>("Tsh");

                    b.Property<string>("Urea");

                    b.Property<string>("UserId");

                    b.Property<string>("Vdrl");

                    b.Property<string>("Vitaminas_B");

                    b.Property<bool>("WasDeleted");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("medicalassitent.web.Data.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.Property<bool>("WasDeleted");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("medicalassitent.web.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("medicalassitent.web.Data.Entities.Analytics", b =>
                {
                    b.HasOne("medicalassitent.web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("medicalassitent.web.Data.Entities.DocumentType", b =>
                {
                    b.HasOne("medicalassitent.web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("medicalassitent.web.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("medicalassitent.web.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("medicalassitent.web.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("medicalassitent.web.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
