using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace medicalassitent.web.Migrations
{
    public partial class AddAnalitics : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Analytics",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Id_Paciente = table.Column<int>(nullable: false),
                    Id_Medico = table.Column<int>(nullable: false),
                    Fecha = table.Column<DateTime>(nullable: false),
                    No_Historia = table.Column<string>(nullable: true),
                    Ac_Urico = table.Column<string>(nullable: true),
                    Albumina = table.Column<string>(nullable: true),
                    Amilasa = table.Column<string>(nullable: true),
                    Billirubina = table.Column<string>(nullable: true),
                    Calcio = table.Column<string>(nullable: true),
                    Ck_Total = table.Column<string>(nullable: true),
                    Ck_MB = table.Column<string>(nullable: true),
                    Col_Total = table.Column<string>(nullable: true),
                    Col_HDL = table.Column<string>(nullable: true),
                    Col_LDL = table.Column<string>(nullable: true),
                    Col_VLDL = table.Column<string>(nullable: true),
                    CurGluc_Hora = table.Column<string>(nullable: true),
                    Cloro = table.Column<string>(nullable: true),
                    Creatinina = table.Column<string>(nullable: true),
                    Ferritina = table.Column<string>(nullable: true),
                    Fos_Alcalina = table.Column<string>(nullable: true),
                    FosfAcTotal = table.Column<string>(nullable: true),
                    FosfAcNoProst = table.Column<string>(nullable: true),
                    FosfAcProst = table.Column<string>(nullable: true),
                    Fosfolipidos = table.Column<string>(nullable: true),
                    Fosforo = table.Column<string>(nullable: true),
                    Gluc_Ayunas = table.Column<string>(nullable: true),
                    Gluc_Prandial = table.Column<string>(nullable: true),
                    Gluc_Gluc = table.Column<string>(nullable: true),
                    Gluc_Capilar = table.Column<string>(nullable: true),
                    Hem_Gluc = table.Column<string>(nullable: true),
                    GGTP = table.Column<string>(nullable: true),
                    Hi_Serico = table.Column<string>(nullable: true),
                    Cap_Hierro = table.Column<string>(nullable: true),
                    Inm_lgA = table.Column<string>(nullable: true),
                    Inm_Lgc = table.Column<string>(nullable: true),
                    Inm_Lgm = table.Column<string>(nullable: true),
                    Ldh = table.Column<string>(nullable: true),
                    Lipasa = table.Column<string>(nullable: true),
                    Lip_Tot = table.Column<string>(nullable: true),
                    Magnesio = table.Column<string>(nullable: true),
                    Microal_Cuant = table.Column<string>(nullable: true),
                    Potasio_K = table.Column<string>(nullable: true),
                    Prot_Total = table.Column<string>(nullable: true),
                    Prot_Frac = table.Column<string>(nullable: true),
                    Sodio_Na = table.Column<string>(nullable: true),
                    SGCT = table.Column<string>(nullable: true),
                    SGTP = table.Column<string>(nullable: true),
                    Trigliceridos = table.Column<string>(nullable: true),
                    Tropl_Cualit = table.Column<string>(nullable: true),
                    TropT_Cualit = table.Column<string>(nullable: true),
                    TropT_Cuanti = table.Column<string>(nullable: true),
                    Urea = table.Column<string>(nullable: true),
                    Bacil_En = table.Column<string>(nullable: true),
                    Bacil_Ser = table.Column<string>(nullable: true),
                    Cultivo = table.Column<string>(nullable: true),
                    TincGram_en = table.Column<string>(nullable: true),
                    Cont_Sangre = table.Column<string>(nullable: true),
                    Cont_Nasal = table.Column<string>(nullable: true),
                    Cont_Retic = table.Column<string>(nullable: true),
                    Eritrosedimentacion = table.Column<string>(nullable: true),
                    Falcemia = table.Column<string>(nullable: true),
                    Hemograma = table.Column<string>(nullable: true),
                    Hemotozoarios = table.Column<string>(nullable: true),
                    Tiemp_Prot = table.Column<string>(nullable: true),
                    Tiemp__Tromb = table.Column<string>(nullable: true),
                    Tiemp_Sang = table.Column<string>(nullable: true),
                    Tiemp_Coag = table.Column<string>(nullable: true),
                    Ant_Feb = table.Column<string>(nullable: true),
                    ASO_Latex = table.Column<string>(nullable: true),
                    ASO_Cuant = table.Column<string>(nullable: true),
                    C3 = table.Column<string>(nullable: true),
                    C4 = table.Column<string>(nullable: true),
                    Dengue_Lgg = table.Column<string>(nullable: true),
                    Dengue_Lgm = table.Column<string>(nullable: true),
                    Fac_Latex = table.Column<string>(nullable: true),
                    Fac_Cuant = table.Column<string>(nullable: true),
                    HTLV = table.Column<string>(nullable: true),
                    Lep_Lgg = table.Column<string>(nullable: true),
                    Lep_Lgm = table.Column<string>(nullable: true),
                    Pcr_Latex = table.Column<string>(nullable: true),
                    Pcr__Cuant = table.Column<string>(nullable: true),
                    PCR_Ultra = table.Column<string>(nullable: true),
                    Prueba_Orina = table.Column<string>(nullable: true),
                    Prueba_Sangre = table.Column<string>(nullable: true),
                    Tb_Micodot = table.Column<string>(nullable: true),
                    Tip_Sang = table.Column<string>(nullable: true),
                    Prueb_Directa = table.Column<string>(nullable: true),
                    Prueb_Indirecta = table.Column<string>(nullable: true),
                    Vdrl = table.Column<string>(nullable: true),
                    Acido_Folico = table.Column<string>(nullable: true),
                    Antic_Antit = table.Column<string>(nullable: true),
                    Anti_Hav = table.Column<string>(nullable: true),
                    AntiHav_Lgg = table.Column<string>(nullable: true),
                    AntiHbc = table.Column<string>(nullable: true),
                    AntiHbe = table.Column<string>(nullable: true),
                    Hbcg = table.Column<string>(nullable: true),
                    Cortisol = table.Column<string>(nullable: true),
                    Cort_Muest = table.Column<string>(nullable: true),
                    Cort_Pm = table.Column<string>(nullable: true),
                    Elect_Hb = table.Column<string>(nullable: true),
                    Elect_MAcid = table.Column<string>(nullable: true),
                    Estrogenos_Totales = table.Column<string>(nullable: true),
                    Fsh = table.Column<string>(nullable: true),
                    HepatB_Ag = table.Column<string>(nullable: true),
                    Hepat_HVC = table.Column<string>(nullable: true),
                    Antigeno_Ag = table.Column<string>(nullable: true),
                    HIV = table.Column<string>(nullable: true),
                    Hormona_Basal = table.Column<string>(nullable: true),
                    Hormona_Est = table.Column<string>(nullable: true),
                    Inmunoglobina = table.Column<string>(nullable: true),
                    Lh = table.Column<string>(nullable: true),
                    Progesterona = table.Column<string>(nullable: true),
                    Prolactina = table.Column<string>(nullable: true),
                    T3 = table.Column<string>(nullable: true),
                    T3_Libre = table.Column<string>(nullable: true),
                    T4 = table.Column<string>(nullable: true),
                    T4_Libre = table.Column<string>(nullable: true),
                    Tsh = table.Column<string>(nullable: true),
                    Testoterona = table.Column<string>(nullable: true),
                    Tiroglobulina = table.Column<string>(nullable: true),
                    Toxo_Lgg = table.Column<string>(nullable: true),
                    Toxo_Lgm = table.Column<string>(nullable: true),
                    Vitaminas_B = table.Column<string>(nullable: true),
                    Ana = table.Column<string>(nullable: true),
                    Anti_Dna = table.Column<string>(nullable: true),
                    Celulas_Le = table.Column<string>(nullable: true),
                    Monotest = table.Column<string>(nullable: true),
                    Alfp = table.Column<string>(nullable: true),
                    Cea = table.Column<string>(nullable: true),
                    Cea_15 = table.Column<string>(nullable: true),
                    Cea_19 = table.Column<string>(nullable: true),
                    Cea_125 = table.Column<string>(nullable: true),
                    Antidoping_CocMar = table.Column<string>(nullable: true),
                    Antidoping_Panel = table.Column<string>(nullable: true),
                    Depur_Creat = table.Column<string>(nullable: true),
                    Examen_Orina = table.Column<string>(nullable: true),
                    Proteina_Orina = table.Column<string>(nullable: true),
                    Proteina_BJ = table.Column<string>(nullable: true),
                    Coprologico = table.Column<string>(nullable: true),
                    Coprologico_X2 = table.Column<string>(nullable: true),
                    Coprologico_X3 = table.Column<string>(nullable: true),
                    Coprologico_Conc = table.Column<string>(nullable: true),
                    Dig_Heces = table.Column<string>(nullable: true),
                    H_Pilory = table.Column<string>(nullable: true),
                    Oxiuros_Cinta = table.Column<string>(nullable: true),
                    Rotavirus = table.Column<string>(nullable: true),
                    Sust_Reduc = table.Column<string>(nullable: true),
                    Sangre_Oculta = table.Column<string>(nullable: true),
                    Colera = table.Column<string>(nullable: true),
                    Otros = table.Column<string>(nullable: true),
                    Dx = table.Column<string>(nullable: true),
                    UserId = table.Column<string>(nullable: true),
                    WasDeleted = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Analytics", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Analytics_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Analytics_UserId",
                table: "Analytics",
                column: "UserId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Analytics");
        }
    }
}
